- ros_topic_name: /bluerov/odom   # <--- ROS side name
  gz_topic_name: /model/bluerov/odometry # <--- Gazebo side name
  ros_type_name: nav_msgs/msg/Odometry
  gz_type_name: gz.msgs.Odometry
  direction: "GZ_TO_ROS"

# Front camera (forward-facing on the bow)
- ros_topic_name: /bluerov/front_cam/image
  gz_topic_name: /bluerov/front_cam/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: "GZ_TO_ROS"
- ros_topic_name: /bluerov/front_cam/camera_info
  gz_topic_name: /bluerov/front_cam/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: "GZ_TO_ROS"