- ros_topic_name: /blueboat/odom   # <--- ROS side name
  gz_topic_name: /model/blueboat/odometry # <--- Gazebo side name (OdometryPublisher default)
  ros_type_name: nav_msgs/msg/Odometry
  gz_type_name: gz.msgs.Odometry
  direction: "GZ_TO_ROS"
